## 1. Import dataset

In [1]:
import sys
sys.path.insert(0, '../../src')
import pandas as pd
import numpy as np

In [2]:
from data.make_dataset import *
X_train, y_train, X_val, y_val, X_test, y_test = load_sets(path='../../data/processed/')

In [3]:
print(X_train.shape), print(y_train.shape)

(8111999, 12)
(8111999,)


(None, None)

In [4]:
print(X_train)

[[-0.9957380269644961 1 0 ... 0.20431196405789043 1.7479935428180702 0.0]
 [-0.7886056935133886 1 0 ... -2.2066091586309255 0.47830807387632734 0.0]
 [-0.5740757767247417 1 0 ... -0.14010533918336898 -1.3733165683303807
  0.0]
 ...
 [-0.46064616554913523 0 1 ... 1.4097725254022984 1.7479935428180702 0.0]
 [0.4850115710996706 0 0 ... 0.03210331243726073 1.0073436859353868 0.0]
 [1.2642236826538367 0 0 ... -0.4845226424246284 0.6899223186999511 0.0]]


In [18]:
X_train

array([[206.0, 1.0, 0.0, ..., 0.20431196405789043, 1.7479935428180702,
        0.0],
       [341.0, 1.0, 0.0, ..., -2.2066091586309255, 0.47830807387632734,
        0.0],
       [506.0, 1.0, 0.0, ..., -0.14010533918336898, -1.3733165683303807,
        0.0],
       ...,
       [595.0, 0.0, 1.0, ..., 1.4097725254022984, 1.7479935428180702,
        0.0],
       [1295.0, 0.0, 0.0, ..., 0.03210331243726073, 1.0073436859353868,
        0.0],
       [1883.0, 0.0, 0.0, ..., -0.4845226424246284, 0.6899223186999511,
        0.0]], dtype=object)

In [12]:
X_train.dtype

dtype('O')

In [17]:
# Identify non-numeric columns
non_numeric_columns = [i for i in range(X_train.shape[1]) if not np.issubdtype(X_train[:, i].dtype, np.number)]

# Convert non-numeric columns to numeric (e.g., float)
for column_idx in non_numeric_columns:
    column = X_train[:, column_idx]
    unique_values = np.unique(column)  # Get unique values in the column
    value_to_index = {value: idx for idx, value in enumerate(unique_values)}
    
    # Create a new array with the same shape as the original column
    converted_column = np.zeros(column.shape, dtype=float)
    
    # Map each unique value to its corresponding index and fill the converted_column
    for unique_value, idx in value_to_index.items():
        converted_column[column == unique_value] = idx
    
    X_train[:, column_idx] = converted_column

# Check data types after conversion
data_types = [X_train[:, i].dtype for i in range(X_train.shape[1])]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
print(X_train.dtype)
print(X_train)

In [5]:
print(y_train)

[-0.31391783 -0.50182474 -1.22936172 ... -0.89209292  1.17970114
 -0.04892092]


In [6]:
print(X_val.shape), print(y_val.shape)

(2704000, 12)
(2704000,)


(None, None)

In [7]:
print(X_test.shape), print(y_test.shape)

(2704000, 12)
(2704000,)


(None, None)

In [ ]:
print(X_test)

In [ ]:
print(y_test)

### Check Missing value

In [ ]:
# Check missing values in the training dataset
train_missing = np.isnan(X_train)

# Check missing values in the testing dataset
test_missing = np.isnan(X_test)

# Check missing values in the validation dataset
validate_missing = np.isnan(X_val)

## Baseline model

In [8]:
from models.null import NullRegressor
base_model = NullRegressor()
y_base = base_model.fit_predict(y_train)
from models.predict_model import print_regressor_scores
print_regressor_scores(y_preds=y_base, y_actuals=y_train, set_name='Training')

RMSE Training: 1.0004323491335267
MAE Training: 0.7466010716968183
R2_score Training: 0.0


In [9]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn import linear_model
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
import xgboost as xgb
from sklearn.neighbors import KNeighborsRegressor
from sklearn.ensemble import ExtraTreesRegressor
from sklearn.ensemble import BaggingRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

## Linear regression

In [10]:
lr = LinearRegression()

In [11]:
lr.fit(X_train, y_train)

ValueError: setting an array element with a sequence.

In [ ]:
y_pred_lr = lr.predict(X_val)

lr_mse = mean_squared_error(y_val, y_pred_lr)
lr_r2 = r2_score(y_val, y_pred_lr)
lr_mae = mean_absolute_error(y_val,y_pred_lr)

print("Mean Squared Error:", lr_mse)
print("Mean Absolute Error (MAE):", lr_mae)
print("R-squared:", lr_r2)